// Code generated by counterfeiter. DO NOT EDIT.
package reconcilersfakes

import (
	sync "sync"

	v1alpha1 "github.com/pivotal-cf/ism/pkg/apis/osbapi/v1alpha1"
	reconcilers "github.com/pivotal-cf/ism/pkg/internal/reconcilers"
	v2 "github.com/pmorie/go-open-service-broker-client/v2"
)

type FakeKubeServiceRepo struct {
	CreateStub        func(*v1alpha1.Broker, v2.Service) (*v1alpha1.BrokerService, error)
	createMutex       sync.RWMutex
	createArgsForCall []struct {
		arg1 *v1alpha1.Broker
		arg2 v2.Service
	}
	createReturns struct {
		result1 *v1alpha1.BrokerService
		result2 error
	}
	createReturnsOnCall map[int]struct {
		result1 *v1alpha1.BrokerService
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeKubeServiceRepo) Create(arg1 *v1alpha1.Broker, arg2 v2.Service) (*v1alpha1.BrokerService, error) {
	fake.createMutex.Lock()
	ret, specificReturn := fake.createReturnsOnCall[len(fake.createArgsForCall)]
	fake.createArgsForCall = append(fake.createArgsForCall, struct {
		arg1 *v1alpha1.Broker
		arg2 v2.Service
	}{arg1, arg2})
	fake.recordInvocation("Create", []interface{}{arg1, arg2})
	fake.createMutex.Unlock()
	if fake.CreateStub != nil {
		return fake.CreateStub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.createReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeKubeServiceRepo) CreateCallCount() int {
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	return len(fake.createArgsForCall)
}

func (fake *FakeKubeServiceRepo) CreateCalls(stub func(*v1alpha1.Broker, v2.Service) (*v1alpha1.BrokerService, error)) {
	fake.createMutex.Lock()
	defer fake.createMutex.Unlock()
	fake.CreateStub = stub
}

func (fake *FakeKubeServiceRepo) CreateArgsForCall(i int) (*v1alpha1.Broker, v2.Service) {
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	argsForCall := fake.createArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeKubeServiceRepo) CreateReturns(result1 *v1alpha1.BrokerService, result2 error) {
	fake.createMutex.Lock()
	defer fake.createMutex.Unlock()
	fake.CreateStub = nil
	fake.createReturns = struct {
		result1 *v1alpha1.BrokerService
		result2 error
	}{result1, result2}
}

func (fake *FakeKubeServiceRepo) CreateReturnsOnCall(i int, result1 *v1alpha1.BrokerService, result2 error) {
	fake.createMutex.Lock()
	defer fake.createMutex.Unlock()
	fake.CreateStub = nil
	if fake.createReturnsOnCall == nil {
		fake.createReturnsOnCall = make(map[int]struct {
			result1 *v1alpha1.BrokerService
			result2 error
		})
	}
	fake.createReturnsOnCall[i] = struct {
		result1 *v1alpha1.BrokerService
		result2 error
	}{result1, result2}
}

func (fake *FakeKubeServiceRepo) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeKubeServiceRepo) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ reconcilers.KubeServiceRepo = new(FakeKubeServiceRepo)
